DefaultContentLanguage: en
languageCode: en

theme:
  ["github.com/fundor333/macia-indiweb", "github.com/fundor333/macia-image"]

taxonomies:
  category: categories
  tag: tags
  micropub: micropub
  phototags: phototags

enableRobotsTXT: true
Paginate: 8
enableGitInfo: true
related:
  includeNewer: true
  threshold: 70
  toLower: false
  indices:
    - name: categories
      weight: 40
    - name: title
      weight: 30
    - name: description
      weight: 30
    - name: tags
      weight: 10
    - name: meta
      weight: 10
    - name: date
      weight: 10

outputFormats:
  SearchIndex:
    baseName: search
    mediaType: application/json
outputs:
  section:
    - HTML
    - RSS
  home:
    - HTML
    - RSS
    - SearchIndex
  page:
    - html

sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5

