main:
  - name: home
    url: /
    weight: -10
  - name: "blog"
    weight: 10
    url: "/post/"
  - name: cv
    url: /cv/
    weight: 30
  - name: "photos"
    weight: 20
    url: "/photos"
  - name: "feeds"
    weight: 70
    url: "/feeds"
