main:
  - name: home
    url: /
    weight: -10
  - name: "blog"
    weight: 10
    url: "/post/"
  - name: cosplay
    url: /cosplay/
    weight: 30
  - name: "photos"
    weight: 20
    url: "/photos"
  - name: "feeds"
    weight: 70
    url: "/feeds"
